### ISSUE TITLE
old .pdf files for data dictionary file manifest

### ISSUE THREAD

**Issue by ergonyc** [ASAP-CRN/harmonized-wf-dev#49]
Should be removed:

- [ ] https://github.com/ASAP-CRN/harmonized-wf-dev/blob/main/ASAP_CRN_data_dictionary.pdf
- [ ] https://github.com/ASAP-CRN/harmonized-wf-dev/blob/main/ASAP_CRN_file_manifest.pdf

**Comment by kfang4** [comment]
Removed: https://github.com/ASAP-CRN/harmonized-wf-dev/pull/50
